version: '2.2'

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    #build: ./docker/php/
    image: php:fpm-alpine
    container_name: php
    links:
      - mariadb:mysql
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
  mariadb:
    image: mariadb:latest
    container_name: database
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/opt/data
    command: --init-file /opt/data/migration.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=lempdb
      - MYSQL_USER=lemp
      - MYSQL_PASSWORD=lemppassword 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mariadb
    ports:
      - 8183:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_ARBITRARY: 1
